---
# Registro del Servicio.
apiVersion: v1
kind: Service
metadata:
  name: cliente2-servicio
  namespace: default
spec:
  type: NodePort
  selector:
    app: cliente2
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31000