apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: dl-vol01-pvc
 labels:
   billingType: hourly
   region: us-south
   zone: dal10
spec:
 accessModes:
   - ReadWriteMany
 resources:
   requests:
     storage: 20Gi
 storageClassName: ibmc-file-gold